- README.md
> Editorial test

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Removed language specific to electricity as we may include embodied emissions in the standard
> Refine Purpose

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Pending our discussion of RECs and offsets, this section prohibits offsets and EACs
> Added Exclusions, specifically offsets and EACs

- README.md
- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Setting the mission for the SCI by answering the market perspective questions
> Added answers to introduction questions on the market perspective for the SCI

- .vscode/settings.json
- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Methodology
-Update operational emissions to include energy & carbon intensity
-Modify variables to accomodate for operational & energetic
Exclusion:
-update wording to include various other market-based meausres
> Updating Methodology & Exclusion Information

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Established the boundary requirement. Based on discussion in issue #56
> Boundary Inclusion Requirement

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Energy consumption in kwh and matching software boundary per the discussion in issue #40
> Energy Boundary

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Moved potential action discussion from body to intro
> Move action discussion

- Software_Carbon_Intensity/Index.yaml
- YAML file updated with SCI Spec details
> YAML file updated

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Addressing discussion conclusion from #27
> Added use of granular data for SCI calculation

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Added segment on choosing R value from a preset list and a placeholder section to specify that preset list
> Added segment on choosing R value from a preset list

- CITATION.cff
> added citation for the SCI

- CITATION.cff
Inspired by @atg-abhishek - not something I was familiar with before!
> Add orc-id for CLJ to file

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Our scope was left over from the very first commit. Created a new scope from **existing content** in the doc to reflect our latest thinking.
> Updating the scope to reflect latest content

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
added a baseline for comparison to determine savings potential.
> Baseline comparison for savings

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
moving references, dictionary, and terminology to bottom. 
Adding header to 'steps to calculate' 
No changes to text or wording
> reordering

- Software_Carbon_Intensity/index.yaml
> Index.yaml file updated

- .vscode/settings.json
- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
- Moved sections around so they were laid out in the doc like the "steps" section in our into.
- Normalized language to use "quantify", "measure" and "calculate".
- Updated lab-based vs. real-world measurements to use the language of measurements for real-world telemetry and calculation for numbers based on models.
A number of other changes are in here also... appols.
> Restructured sections to flow like the procedure

- Software_Carbon_Intensity/index.yaml
- Yaml file updated with Alpha prefix
- Approve date added
> [Consistency Review] Yaml file updated with Alpha prefix

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> [Consistency Review] Minor grammar updates

- Software_Carbon_Intensity/case_study_template.md
> Added template for case studies

- case-studies/eshoppen
This is a case study for calculation of SCI score for eshoponWeb web application. The initial draft is done for the App server now and will be extended in future for other components that are excluded for now.
> Eshoppen case study initial draft

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
adding End user devices, IoT devices and Edge devices to boundaries, according to issue#267
> Adding multiple devices to boundaries exemples

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Updated the Software Carbon Intensity Standard to include guidance on taking into account data center energy efficiency in the Software Boundary section
> Update Software_Carbon_Intensity.md closes #266

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Added context for SCI reduction for software roles
> Added context for SCI reduction for software roles

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
1. 'scale' should be first step in the process, as it's the key measure of success
2. 'what' is a bit misleading, and is best defined as a boundary  -> 'bound' is a good verb
3. 'how' is a step that best follows the boundary step -> 'bound' is a verb
> Procedure Flow Updates

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Reversed hierarchy from complex formula at the top and simple formula at the bottom. Now you build knowledge as you go down: SCI = C / R -> SCI = (O + M)/R -> SCI = (O formula + M formula)/R.
> Re-order formula for clarity

- Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
Implementing issue/discussion #339
> Add Carbon Definition

- SPEC.md
This PR brings the GitHub version in line with the Approved v1.0 published ISO version
Once approved - Dev will be merged into Main to publish v1.1
> Approved Dev v1.1 

- README.md
Fixing broken link in the Readme file
> Fixing broken link in the Readme file
